var questionsRight = 0;

var problems = [ 
	{ "question" : "In the first film, arguably the greatest of all time, what is the name of the limo driver that picks up John from the airport?", a : "Anthony", b : "Chris", c : "Argyle", d : "Adrian"},
	{ "question" : "John’s wife Holly is listed in the building directory with her maiden name, Gennaro. What does she say is the reason for doing this?", a : "to get ahead in the corporate world" , b : "it’s a Japanese company", c : "not sure if John was coming to LA", d : "just to keep things simple for now", answer : a},
	{ "question" : "While the building is under siege by Hans Gruber and associates, one of Holly’s coworkers, Harry Ellis, (arguably God’s Greatest gift) offers to help the terrorist make a deal. How does he convince Hans?", a : "Hans, bubby, i’m your white knight", b : "Hans, Hans, Hans, Hans, Hans, Hans Come’on Hans", c : "Hans I can giftwrap this cowboy for you", d : "Hans do you like your steak well done", answer : a},
	{ "question" : "In the second film, arguably the 2nd greatest of all time, John is at the airport in his in laws' car to pick up Holly. Which airport is this ?", a : "IAD - Washington Dulles International Airport", b : "BOS - Boston Logan International Airport", c : "BWI - Baltimore Washington International Airport", d : "LGA - LaGuardia International Airport", answer : a},
	{ "question" : "Reporter Samantha Coleman is at the airport trying to get a story while waiting for General Esperanza’s flight to arrive. After getting no comment from the guys from the state department, she then also gets a freezing cold shoulder from an ex Special Forces commander while walking through the airport. Who is the commander?", a : "Lt Johnson", b : "Brigadier General Francis X Hummel", c : "Colonel William Stuart", d : "Major Benson Winifred Payne", answer : c},
	{ "question" : "In the 3rd Die Hard film, arguably the 3rd greatest of all time, John is forced to run around NY doing what Hans Gruber’s brother tells him to do. John is nursing a pretty solid hangover, and on the way to their first stop in Harlem, officers are discussing 14 dump trucks were stolen overnight from a yard in Staten Island. Who did Officer Lamber suggest the trucks were stolen by?", a : "Simon Gruber", b : "John’s Land Lady", c : "Zeus", d : "Santa Claus", answer : b},
	{ "question" : "Midway through the film John teams up with a truck driver named Jerry to drive through the aqueduct tunnel. Jerry solves a riddle for John. “What is 21 out of 42?” Who does Jerry tell John that the 21st president is?", a : "Hilary A. Clinton", b : "Grover A. Cleveland", c : "James A. Garfield" , d : "Chester A. Arthur", answer : d},
]


$('#quiz')